# Generated by Django 5.2.15 on 2026-07-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_reward_task_cointransaction_rewardredemption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='status',
            field=models.CharField(choices=[('pending', 'Em Revisão'), ('approved', 'Aprovada')], default='approved', max_length=15),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
