# Generated by Django 5.2.15 on 2026-07-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_taskcompletion_status_alter_reward_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='status',
            field=models.CharField(choices=[('pending', 'Em Revisão'), ('approved', 'Aprovada'), ('rejected', 'Recusada')], default='approved', max_length=15),
        ),
    ]
