# Generated by Django 5.2.15 on 2026-07-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_taskcompletion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='category',
            field=models.CharField(choices=[('food', 'Vale-Comida'), ('eletronics', 'Eletronicos'), ('clothing', 'Roupa'), ('generic', 'Outros')], default='generic', max_length=20),
        ),
    ]
